### ISSUE TITLE
Waypoint enhance

### ISSUE THREAD

**Issue by Jhezreel708** [mmopluginteam/mmocore#130]
>**Is your feature request related to a problem? Please describe.**
>A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

So currently waypoint system is still new and doesn't have that much features

**Describe the solution you'd like**

>A clear and concise description of what you want to happen.

I would like to suggest a Spawn on Waypoint option

basically players can choose a waypoint to set their own spawn on, this will be needed
 for most rpg based servers that has towns in it that's discoverable.

also the config would be like

```
**You can set these waypoint as spawn point**
Prontera:
    name: Prontera
    location: 'world 69 71 136 136 0'
    radius: 1.5
    stellium: 3
    default: false
    setable: true

Morroc:
    name: Morroc
    location: 'world 5080 75 5868 136 0'
    radius: 1.5
    stellium: 3
    default: false
    setable: true
**You cannot set this waypoint as spawn point**
deadlyforest1:
    name: Deadlyforest Camp
    location: 'world 40 158 166 186 0'
    radius: 1.5
    stellium: 3
    default: false
    setable: false

UnderwaterCity entrance:
    name: UnderwaterCity entrance
    location: 'world 2597 60 17980 186 0'
    radius: 1.5
    stellium: 3
    default: false
    setable: false
```

This way players can /Fast travel/ per town and also set their own spawn there.
