### ISSUE TITLE
Any crops with "age" attribute can still be harvested regardless of the age of the target block.

### ISSUE THREAD

**Issue by AshenGaming** [mmopluginteam/mmocore#75]
*Raised by **@SlipperySmurf** on the Discord.*

**Describe the bug**
When using restrictions, the following does not work:

```yaml
WOODEN_HOE:
    can-mine:
    - vanilla{type=CARROTS;age=7}
    - vanilla{type=RED_MUSHROOM}
    - vanilla{type=BROWN_MUSHROOM}
    - vanilla{type=COCOA;age=2}
    - vanilla{type=POTATOES;age=7}
    - vanilla{type=SUGAR_CANE;age=7}
    - vanilla{type=NETHER_WART;age=3}
    - vanilla{type=MELON}
    - vanilla{type=WHEAT;age=7}
    - vanilla{type=BEETROOTS;age=3}
    - vanilla{type=PUMPKIN}
```

Any of the crops with "age" specified can be harvested, regardless of what age the target block is.

**Expected behavior**
The `can-mine` restrictions should prevent a block such as carrots from being broken unless they are specifically `age=7`.

**Screenshots**
https://cdn.discordapp.com/attachments/715756114502877257/715910135007936614/2020-05-29_07-50-45.mp4

**Server info:**
 - Spigot Build & Version
 - Plugin Version
 - Potential plugins linked to the issue
