### ISSUE TITLE
Custom Model Data in Skills GUI doesn't work.

### ISSUE THREAD

**Issue by AshenGaming** [mmopluginteam/mmocore#76]
*Raised by **@cookieXL** on the Discord.*

**Describe the bug**
Using custom model data on the skills GUI does not work for me, when using MMOItems and its custom model data selector it works fine.

**To Reproduce**
```yaml
next:
        slots: [16]
        function: next
        item: GRAY_DYE:59001
        name: '&aNext'
        lore: {}
```
**Expected behavior**
The Skills item in the GUI should show the provided custom model data.

**Server info:**
 - Spigot Build & Version
 - Plugin Version
 - Potential plugins linked to the issue
